### ISSUE TITLE
post request are not debounced

### ISSUE THREAD

**Issue by MykCib** [supermemoryai/supermemory#146]
When I press the button to add a new memory multiple times before the current POST request completes, multiple requests are sent simultaneously. This ends up adding several memories with the same title.

https://github.com/user-attachments/assets/0254075e-8c5c-4fdb-806f-30e94a2670bb

**Comment by Sama-004** [comment]
@Welding-Torch this issue is fixed ig

**Comment by Welding-Torch** [comment]
@Sama-004 Nope, it isn't fixed. I can still reproduce it 
![image](https://github.com/user-attachments/assets/0842dbc1-7d8c-41a1-a10e-f5e7d6d203e9)
![image](https://github.com/user-attachments/assets/31af6973-9768-445b-9dc3-b01abaa667d0)
Spamming the save button results in the same memory being saved multiple times.

[This PR](https://github.com/supermemoryai/supermemory/pull/155) by @yh010 will fix the issue (thanks Yash!), but still needs to be merged by @Dhravya

**Comment by ameeetgaikwad** [comment]
Is this fixed ?
